version: '3.3'
services:
  healthcheck:
    image: 'hc'
    ports:
      - target: 8000
        published: 10000
        protocol: tcp
        mode: host
    env_file:
      - .env
    command: bash -c 'while !</dev/tcp/tasks.deployer_database/3306; do sleep 1; done; /opt/healthchecks/manage.py'
